Repository notmarek/BeFake, pull requests merged in 2023-04, with the labels that each got.

#65 Update README.md
  README.md
Labels: documentation

#75 Fixed 'old-post' post error 400
  BeFake/models/post.py
Labels: bug

#80 Login overhaul + fixup
  BeFake/BeFake.py
  BeFake/__main__.py
Labels: critical
